src/canteen/urls.py
from django.urls import path
from .views import flat_views
from .views import menu_views


app_name = 'canteen'

urlpatterns = [
    path('menu-list', menu_views.menu_list, name='menu_index'),
    path('menu-add/', menu_views.menu_add, name='menu_add'),
    path('menu-edit-<int:id>/', menu_views.menu_edit, name='menu_edit'),
    path('menu-delete-<int:id>/', menu_views.menu_delete, name='menu_delete'),
    path('flat-list/', flat_views.flat_list, name='flat_index'),
    path('flat-add/', flat_views.flat_add, name='flat_add'),
    path('flat-edit-<int:id>/', flat_views.flat_edit, name='flat_edit'),
    path('flat-delete-<int:id>/', flat_views.flat_delete, name='flat_delete'),
]

src/gestCantineADA/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('canteen/', include('canteen.urls')),
    path('admin/', admin.site.urls),
]

src/canteen/models/flat_model.py
from django.db import models
from base.models.helpers.named_date_time_model import NamedDateTimeModel

# Create your models here.

class FlatModel(NamedDateTimeModel):
    summary = models.CharField(max_length=100, verbose_name="Description ")


    def __str__(self):
        return f"{self.name}"    

    class Meta:
        verbose_name = "Plat"
        verbose_name_plural = "Plats"

src/canteen/models/menu_model.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel

# Create your models here.

class MenuModel(DateTimeModel):
    flat = models.OneToOneField("canteen.FlatModel", on_delete=models.CASCADE, verbose_name="Plat ")


    def __str__(self):
        return f"{self.flat}"    

    class Meta:
        verbose_name = "Menu"
        verbose_name_plural = "Menus"

src/canteen/forms/flat_forms.py
from django import forms
from ..models.flat_model import FlatModel


class FlatForm(forms.ModelForm):

    class Meta:
        model = FlatModel
        fields = ['name', 'summary']


        labels ={
            'name': 'Nom du plat',
        }

        widgets ={
            'summary': forms.Textarea()
        }

src/canteen/forms/menu_forms.py
from django import forms
from ..models.menu_model import MenuModel


class MenuForm(forms.ModelForm):

    class Meta:
        model = MenuModel
        fields = ['flat'] 

src/base/views.py
from django.shortcuts import render

# Create your views here.

src/canteen/views/flat_views.py
from django.shortcuts import render, redirect
from ..forms.flat_forms import FlatForm
from ..models.flat_model import FlatModel
from django.contrib import messages


# Create your views here.

def flat_list(request):

    context = {}
    search_field = request.GET.get('search_field')
    if search_field:
        flats = FlatModel.objects.filter(name__icontains=search_field, status=True)
        numbers_flats = flats.count()
        context['flats'] = flats
        context['search_field'] = search_field
        context['numbers_flats'] = numbers_flats
    else:
        flats =  FlatModel.objects.filter(status=True)
        numbers_flats = flats.count()
        context['flats'] = flats
        context['numbers_flats'] = numbers_flats

    return render(request, 'pages/plats.html', context)


def flat_add(request):

    context = {
        "title": "Formulaire d'enregistrement d'un plat",
        "submit_btn": "Enregistrer",
    }

    if request.method == "POST":
        flat_form = FlatForm(request.POST)
        if flat_form.is_valid():
            flat_form.save()
            messages.error(request, " Plat ajouté avec succès ! ")
            return redirect("canteen:flat_index")
        else:
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")
    else:
        flat_form = FlatForm()
    context['form'] = flat_form    

    return render(request, 'pages/forms.html', context)


def flat_edit(request, id):

    context = {
        "title": "Formulaire de modification d'un plat",
        "submit_btn": "Modifier",
    }

    flat = FlatModel.objects.get(id = id)

    if request.method == "POST":
        flat_form = FlatForm(request.POST, instance=flat)
        if flat_form.is_valid():
            flat_form.save()
            messages.success(request, " Plat modifié avec succès ! ")
            return redirect("canteen:flat_index")
        else:
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")
    else:
        flat_form = FlatForm(instance=flat)
    context['form'] = flat_form    

    return render(request, 'pages/forms.html', context)


def flat_delete(request, id):

    flat = FlatModel.objects.get(id = id)
    flat.status = False
    flat.save()
    messages.success(request, " Plat suprimé avec succès ! ")
    return redirect("canteen:flat_index") 

src/canteen/views/menu_views.py
from django.shortcuts import render, redirect
from ..forms.menu_forms import MenuForm
from ..models.menu_model import MenuModel
from django.contrib import messages


# Create your views here.

def menu_list(request):

    context = {}
    search_field = request.GET.get('search_field')
    if search_field:
        menus = MenuModel.objects.filter(flat__name__icontains=search_field, status=True)
        numbers_menus = menus.count()
        context['menus'] = menus
        context['search_field'] = search_field
        context['numbers_menus'] = numbers_menus
    else:
        menus =  MenuModel.objects.filter(status=True)
        numbers_menus = menus.count()
        context['menus'] = menus
        context['numbers_menus'] = numbers_menus

    return render(request, 'pages/menus.html', context)


def menu_add(request):

    context = {
        "title": "Formulaire d'enregistrement d'un menu",
        "submit_btn": "Enregistrer",
    }

    if request.method == "POST":
        menu_form = MenuForm(request.POST)
        if menu_form.is_valid():
            menu_form.save()
            messages.success(request, " Menu ajouté avec succès ! ")
            return redirect("canteen:menu_index")
        else:
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")
    else:
        menu_form = MenuForm()
    context['form'] = menu_form    

    return render(request, 'pages/forms.html', context)


def menu_edit(request, id):

    context = {
        "title": "Formulaire de modification d'un menu",
        "submit_btn": "Modifier",
    }

    menu = MenuModel.objects.get(id = id)

    if request.method == "POST":
        menu_form = MenuForm(request.POST, instance=menu)
        if menu_form.is_valid():
            menu_form.save()
            messages.success(request, " Menu modifié avec succès ! ")
            return redirect("canteen:menu_index")
        else:
            messages.error(request, "Erreur dans le formulaire. Veuillez vérifier les champs.")
    else:
        menu_form = MenuForm(instance=menu)
    context['form'] = menu_form    

    return render(request, 'pages/forms.html', context)


def menu_delete(request, id):

    menu = MenuModel.objects.get(id = id)
    menu.status = False
    menu.save()
    messages.success(request, " Menu suprimé avec succès ! ")
    return redirect("canteen:menu_index") 

src/gestCantineADA/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
        <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
        
        {% block title %}
            <title>
                Ma cantine scolaire
            </title>
        {% endblock title %}
        
        
        <!--     Fonts and icons     -->
        <link rel="stylesheet" type="text/css"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
        
        
        <!-- Nucleo Icons -->
        <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet"/>
        
        <!-- Font Awesome Icons -->
        <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
        
        <!-- Material Icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
        
        <!-- CSS Files -->
        <link rel="stylesheet" href="{% static 'assets/css/modal.css' %}">
        
        <link id="pagestyle" href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet"/>
        
        
        <!-- Nepcha Analytics (nepcha.com) -->
        <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
        <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
    </head>
    <body class="g-sidenav-show  bg-gray-100">
        <aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

            <div class="sidenav-header">
                <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
                aria-hidden="true" id="iconSidenav"></i>
                <a class="navbar-brand m-0" href="{% url 'home' %}">
                    <img src="{% static 'assets/img/logo-ct.png' %}" class="navbar-brand-img h-100" alt="main_logo">
                    <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
                </a>
            </div>


            <hr class="horizontal light mt-0 mb-2">

            <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
                <ul class="navbar-nav">


                    <li class="nav-item">
                        <a class="nav-link text-white " href="{% url 'canteen:menu_index' %}">

                            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                                <span class="material-symbols-outlined">menu_book</span>
                            </div>

                            <span class="nav-link-text ms-1">Menus</span>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link text-white " href="{% url 'canteen:flat_index' %}">

                            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                                <span class="material-symbols-outlined">local_cafe</span>
                            </div>

                            <span class="nav-link-text ms-1">Plats</span>
                        </a>
                    </li>

                </ul>
            </div>

        </aside>

        {% block container %}
          
        {% endblock container %}

        {% block footer %}
        
            <main class="main-content border-radius-lg ">

                <div class="container-fluid py-4">
            
                    <footer class="footer py-4  ">
                        <div class="container-fluid">
                            <div class="row align-items-center justify-content-lg-between">
                                <div class="col-lg-6 mb-lg-0 mb-4">
                                    <div class="copyright text-center text-sm text-muted text-lg-start">
                                        © <script>
                                        document.write(new Date().getFullYear())
                                    </script>
                                        ADA
                                    </div>
                                </div>
                            </div>
                        </div>
                    </footer>
            
                </div>
            
            </main>
          
        {% endblock footer %}

        <!--   Core JS Files   -->
        <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
        <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
        <script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
        <script src="{% static 'assets/js/plugins/smooth-scrollbar.min.js' %}"></script>
        <script>
            var win = navigator.platform.indexOf('Win') > -1;
            if (win && document.querySelector('#sidenav-scrollbar')) {
                var options = {
                    damping: '0.5'
                }
                Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
            }
        </script>

        <!-- Github buttons -->
        <script async defer src="https://buttons.github.io/buttons.js"></script>


        <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
        <script src="{% static 'assets/js/material-dashboard.min.js' %}"></script>

        {% block scripts %}
  
        {% endblock scripts %}
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                
                const messages = document.querySelectorAll('.messages');
                const duration = 5000;
        
                messages.forEach(function(message) {
                    setTimeout(function() {
                        message.style.display = 'none';
                    }, duration);
                });
            });
        </script>
    </body>
</html>

src/templates/index.html
{% extends "base.html" %}
{% load static %}


{% block container %}

    <main class="main-content  mt-0">
        <section>
            <div class="page-header min-vh-100">
                <div class="container">
                    <div class="row">
                        <h1 class="text-center">BIENVENUE DANS MA CANTINE</h1>
                    </div>
                </div>
            </div>
        </section>
    </main>
          
{% endblock container %}

src/templates/pages/forms.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Formulaire</title>
{% endblock title %}


{% block container %}

    <main class="main-content  mt-0">
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert-danger" style="color: white;">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
        <section>
            <div class="page-header min-vh-100">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                            <div class="card card-plain">
                                <div class="card-header">
                                    <h4 class="font-weight-bolder">{{ title }}</h4>
                                </div>
                                <div class="card-body">
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <!-- <div class="input-group input-group-outline mb-3">
                                            <label class="form-label">Libelle</label>
                                            <input type="text" class="form-control" name="name">
                                        </div>
                                        <div class="input-group input-group-outline mb-3">
                                            <label class="form-label">Description</label>
                                            <input type="text" class="form-control" name="summury">
                                        </div> -->
                                        {{ form|crispy }}
                                        <div class="text-center">
                                            <button type="submit"
                                                    class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                                                {{ submit_btn }}
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
          
{% endblock container %}

{% block footer %}
        
    <span></span>

{% endblock footer %}

src/templates/pages/menus.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Liste des menus</title>
{% endblock title %}


{% block container %}

  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert-success" style="color: white;">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">


        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <ul class="navbar-nav  justify-content-start">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'canteen:menu_add' %}">Ajouter un menu</a>
            </li>
          </ul>
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
              <form method="GET">
              <div class="input-group input-group-outline">
                <!-- <label class="form-label"></label> -->
                <input type="text" name="search_field" value="{{ search_field }}" class="form-control" placeholder="Recherche par nom de plat">
              </div>
            </div>
            <ul class="navbar-nav  justify-content-end">
              <li class="nav-item d-flex align-items-center">
                <button class="btn btn-outline-primary btn-sm mb-0 me-3">Recherche</button>
              </li>
            </ul>
        </form>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Liste des menus ({{ numbers_menus }})</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Date</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Plat</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for menu in menus  %}
                    
                      <tr>
                        <td>
                          <div class="d-flex px-2 py-1">
                            <div class="d-flex flex-column justify-content-center">
                              <h6 class="mb-0 text-sm">{{ menu.created_at|date:"D d M Y" }}</h6>
                            </div>
                          </div>
                        </td>
                        <td>
                          <div class="d-flex px-2 py-1">
                            <div class="d-flex flex-column justify-content-center">
                              <h6 class="mb-0 text-sm">{{ menu.flat|capfirst }}</h6>
                            </div>
                          </div>
                        </td>
                        <td class="align-middle text-center text-sm">
                          <button class="badge badge-sm bg-gradient-success">
                            <a href="{% url 'canteen:menu_edit' menu.id  %}">
                              <i class="fa fa-edit"></i>
                            </a>
                          </button>
                          <button class="badge badge-sm bg-gradient-danger" data-id="{{menu.id}}" onclick="showModal(this)">
                            Supprimer
                          </button>
                        </td>
                      </tr>  

                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer py-4  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>
                ADA
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>

  <div class="modal" id="modal">
    <div class="modal-content">
        <h2>ATTENTION !!</h2>
        <p>Voulez-vous vraiment supprimer ce menu ?</p>
        <button onclick="closeModal()">Non</button>
        <button onclick="confirmDelete()">Oui</button>
    </div>
</div>
          
{% endblock container %}

{% block scripts %}

  <script>
    let Id;

    function showModal(buttonElement) {
        Id = buttonElement.getAttribute('data-id');  
        document.getElementById('modal').style.display = 'flex';  
    }

    function closeModal() {
        document.getElementById('modal').style.display = 'none';     
    }

    function confirmDelete() {
        closeModal();
        window.location.href = "{% url 'canteen:menu_delete' 0 %}".replace(0, Id);
    }
  </script>
  
{% endblock scripts %}

src/templates/pages/plats.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Liste des plats</title>
{% endblock title %}

{% block container %}

  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert-success" style="color: white">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">


        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <ul class="navbar-nav  justify-content-start">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'canteen:flat_add' %}">Ajouter un plat</a>
            </li>
          </ul>
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
              <form method="GET">
              <div class="input-group input-group-outline">
                <!-- <label class="form-label">Recherche par nom</label> -->
                <input type="text" name="search_field" value="{{ search_field }}" class="form-control" placeholder="Recherche par nom de plat"> 
              </div>
            </div>
            <ul class="navbar-nav  justify-content-end">
              <li class="nav-item d-flex align-items-center">
                <button class="btn btn-outline-primary btn-sm mb-0 me-3">Recherche</button>
              </li>
            </ul>
        </form>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Liste des plats ({{ numbers_flats }})</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Libelle</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"></th>
                    </tr>
                  </thead>

                  <tbody>
                    {% for flat in flats  %}

                      <tr>
                        <td>
                          <div class="d-flex px-2 py-1">
                            <div class="d-flex flex-column justify-content-center">
                              <h6 class="mb-0 text-sm">{{ flat.name|capfirst }}</h6>
                            </div>
                          </div>
                        </td>
                        <td class="align-middle text-center text-sm">
                          <button class="badge badge-sm bg-gradient-success">
                            <a href="{% url 'canteen:flat_edit' flat.id  %}">
                              <i class="fa fa-edit"></i>
                            </a>
                          </button>
                          <button class="badge badge-sm bg-gradient-danger" data-id="{{flat.id}}" onclick="showModal(this)">
                            Supprimer
                          </button>
                        </td>
                      </tr>
                    
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer py-4  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>
                ADA
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>

  <div class="modal" id="modal">
    <div class="modal-content">
        <h2>ATTENTION !!</h2>
        <p>Voulez-vous vraiment supprimer ce plat ?</p>
        <button onclick="closeModal()">Non</button>
        <button onclick="confirmDelete()">Oui</button>
    </div>
</div>
          
{% endblock container %}

{% block scripts %}

  <script>
    let Id;

    function showModal(buttonElement) {
        Id = buttonElement.getAttribute('data-id');  
        document.getElementById('modal').style.display = 'flex';  
    }

    function closeModal() {
        document.getElementById('modal').style.display = 'none';     
    }

    function confirmDelete() {
        closeModal();
        window.location.href = "{% url 'canteen:flat_delete' 0 %}".replace(0, Id);
    }
  </script>
  
{% endblock scripts %}